name: seqdata
channels:
  - bioconda
  - conda-forge
  - nodefaults
dependencies:
  - cyvcf2
  - dask
  - natsort
  - pandas
  - pandera
  - pybigwig
  - pysam
  - tqdm
  - typing_extensions
  - xarray
  - zarr