name: seqdata
channels:
  - bioconda
  - conda-forge
  - nodefaults
dependencies:
  - cyvcf2
  - dask
  - joblib
  - more-itertools
  - natsort
  - numcodecs
  - numpy
  - pandas
  - pandera
  - polars
  - pybigwig
  - pysam
  - tqdm
  - typing-extensions
  - xarray
  - zarr